server:
  port: 80

spring:
  application:
    name: cloud-consumer-openfeign-order
  ####Spring Cloud Consul for Service Discovery
  cloud:
    consul:
      host: localhost
      port: 8500
      discovery:
        prefer-ip-address: true #优先使用服务ip进行注册
        service-name: ${spring.application.name}
    openfeign:
      client:
        config:
          default:
            connect-timeout: 20000
            read-timeout: 20000
          cloud-payment-service:
            connect-timeout: 20000
            read-timeout: 20000
      httpclient:
        hc5:
          enabled: true
      compression:
        request:
          enabled: true
          min-request-size: 2048 #最小触发压缩的大小
          mime-types: text/xml,application/xml,application/json #触发压缩数据类型
        response:
          enabled: true
      circuitbreaker:
        enabled: true
        group:
          enabled: true

# feign日志以什么级别监控哪个接口
#logging:
#  level:
#    com:
#      atguigu:
#        cloud:
#          apis:
#            PayFeignApi: debug

resilience4j:
  circuitbreaker:
    configs:
      default:
        failure-rate-threshold: 50
        sliding-window-type: count_based
        sliding-window-size: 6
        minimum-number-of-calls: 6
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 5s
        permitted-number-of-calls-in-half-open-state: 2
        record-exceptions:
          - java.lang.Exception
    instances:
      cloud-payment-service:
        baseConfig: default


#server:
#  port: 80
#
#spring:
#  application:
#    name: cloud-consumer-openfeign-order
#  ####Spring Cloud Consul for Service Discovery
#  cloud:
#    consul:
#      host: localhost
#      port: 8500
#      discovery:
#        prefer-ip-address: true #优先使用服务ip进行注册
#        service-name: ${spring.application.name}
#    openfeign:
#      client:
#        config:
#          default:
#              connectTimeout: 4000 #连接超时时间
#              readTimeout: 4000 #读取超时时间
#    httpclient:
#      hc5:
#        enabled: true